# VacationPy

In [27]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [28]:
PyWeather_csv = "output_data/cities.csv"
cities_df = pd.read_csv(PyWeather_csv)
cities_df.head()

,Unnamed: 0,City,Lat,Lon,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,la huacana,18.9667,18.9667,26.07,53,73,2.30,MX,1619747345
1,1,aksarayskiy,46.7924,46.7924,13.00,50,0,5.00,RU,1619747345
2,2,wanning,18.8003,18.8003,27.22,72,75,1.18,CN,1619747047
3,3,touros,-5.1989,-5.1989,24.00,94,20,3.09,BR,1619747069
4,4,comodoro rivadavia,-45.8667,-45.8667,19.00,45,0,2.06,AR,1619747102

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [29]:
# Store latitude and longitude in locations
locations = cities_df[["Lat", "Lon"]]
weight = cities_df["Humidity"].astype(float)
weight_floats = weight / 100

In [30]:
test = weight_floats.astype(float)

In [31]:
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights = test.astype(float), 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [34]:
ideal_places_df = cities_df.loc[(cities_df["Max Temp"] > 21) &
                                                 (cities_df ["Max Temp"] < 27) &
                                                 (cities_df["Wind Speed"] < 10) &
                                                 (cities_df["Cloudiness"] == 0)]

ideal_places_df

,Unnamed: 0,City,Lat,Lon,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
44,44,camoapa,12.3839,12.3839,24.68,51,0,2.47,NI,1619747239
52,52,doha,25.2867,25.2867,26.00,38,0,2.57,QA,1619747353
98,98,asyut,27.1810,27.1810,22.00,37,0,3.09,EG,1619747203
147,147,huangmei,30.1924,30.1924,24.59,61,0,3.72,CN,1619747401
198,198,wuning,29.2589,29.2589,24.05,51,0,2.51,CN,1619747424
213,213,aksu,41.1231,41.1231,22.16,13,0,2.83,CN,1619747431
245,245,shache,38.4167,38.4167,22.00,11,0,1.27,CN,1619747427
262,262,shaoyang,27.2315,27.2315,23.95,58,0,3.14,CN,1619747448
326,326,broken hill,-31.9500,-31.9500,23.00,28,0,4.63,AU,1619747472
376,376,chapada dos guimaraes,-15.4606,-15.4606,23.00,73,0,1.54,BR,1619747491
400,400,tomatlan,19.9333,19.9333,24.75,78,0,1.88,MX,1619747500
411,411,alice springs,-23.7000,-23.7000,23.33,23,0,5.66,AU,1619747504
412,412,beloha,-25.1667,-25.1667,21.53,68,0,2.47,MG,1619747505
449,449,inhambane,-23.8650,-23.8650,22.21,77,0,2.47,MZ,1619747220
472,472,korla,41.7597,41.7597,24.07,13,0,1.58,CN,1619747526
503,503,codrington,-38.2667,-38.2667,22.31,39,0,4.66,AU,1619747330
552,552,cayenne,4.9333,4.9333,25.00,94,0,1.92,GF,1619747555

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [38]:
hotel_df = ideal_places_df

In [39]:
hotel_df["Hotel Name"] = ""

C:\Users\Robmir\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [40]:
hotel_df

,Unnamed: 0,City,Lat,Lon,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
44,44,camoapa,12.3839,12.3839,24.68,51,0,2.47,NI,1619747239,
52,52,doha,25.2867,25.2867,26.00,38,0,2.57,QA,1619747353,
98,98,asyut,27.1810,27.1810,22.00,37,0,3.09,EG,1619747203,
147,147,huangmei,30.1924,30.1924,24.59,61,0,3.72,CN,1619747401,
198,198,wuning,29.2589,29.2589,24.05,51,0,2.51,CN,1619747424,
213,213,aksu,41.1231,41.1231,22.16,13,0,2.83,CN,1619747431,
245,245,shache,38.4167,38.4167,22.00,11,0,1.27,CN,1619747427,
262,262,shaoyang,27.2315,27.2315,23.95,58,0,3.14,CN,1619747448,
326,326,broken hill,-31.9500,-31.9500,23.00,28,0,4.63,AU,1619747472,
376,376,chapada dos guimaraes,-15.4606,-15.4606,23.00,73,0,1.54,BR,1619747491,
400,400,tomatlan,19.9333,19.9333,24.75,78,0,1.88,MX,1619747500,
411,411,alice springs,-23.7000,-23.7000,23.33,23,0,5.66,AU,1619747504,
412,412,beloha,-25.1667,-25.1667,21.53,68,0,2.47,MG,1619747505,
449,449,inhambane,-23.8650,-23.8650,22.21,77,0,2.47,MZ,1619747220,
472,472,korla,41.7597,41.7597,24.07,13,0,1.58,CN,1619747526,
503,503,codrington,-38.2667,-38.2667,22.31,39,0,4.66,AU,1619747330,
552,552,cayenne,4.9333,4.9333,25.00,94,0,1.92,GF,1619747555,

In [42]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lon"]]

In [43]:
# Add marker layer ontop of heat map
fig = gmaps.figure()
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)


fig

Figure(layout=FigureLayout(height='420px'))